networks:
  cicd-network:

services:
  api:
    build: .
    image: mon-api:latest
    container_name: mon-api

    ports:
      - "8000:8000"

    networks:
      - cicd-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

    restart: unless-stopped