sonar.projectKey=Amin-0810_mon-api
sonar.organization=amin-0810

sonar.projectName=Mon API DevOps

sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11