sonar.projectKey=TON_ORG_mon-api
sonar.organization=TON_ORG

sonar.projectName=Mon API DevOps

sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11